name: Daily Model Retraining

on:
  schedule:
    - cron: "0 0 * * *" # Chạy đúng 00:00 mỗi ngày
  workflow_dispatch: # Vẫn giữ cái này để bạn bấm nút Demo cho cô giáo

jobs:
  run-daily-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Retrain
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
          GDRIVE_SERVICE_ACCOUNT_JSON: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}
        run: python retrain.py
